steps:
  - label: test-build
    command: make test-build
  - label: linux
    command: make build-linux
    agents:
      linux: 'true'
    artifact_paths: bin/*/*/*
  - label: linux-arm
    command: make build-linux-arm
    agents:
      linux-arm: 'true'
    artifact_paths: bin/*/*/*
  - label: bsd
    command: make build-bsd
    agents:
      bsd: 'true'
    artifact_paths: bin/*/*/*
  - label: bsd-arm
    command: make build-bsd-arm
    agents:
      bsd-arm: 'true'
    artifact_paths: bin/*/*/*
  - label: darwin
    command: make build-darwin
    agents:
      darwin: 'true'
    artifact_paths: bin/*/*/*
  - label: windows
    command: make build-windows
    agents:
      windows: 'true'
    artifact_paths: bin/*/*/*
  - label: android
    command: make build-android
    agents:
      android: 'true'
    artifact_paths: bin/*/*/*
  - label: bazel-linux
    command: make bazel-build-linux
    agents:
      linux: 'true'
    artifact_paths: bazel-bin/linux_*_stripped/k0s
  - label: bazel-linux-arm
    command: make bazel-build-linux-arm
    agents:
      linux-arm: 'true'
    artifact_paths: bazel-bin/linux_*_stripped/k0s
  - label: bazel-bsd
    command: make bazel-build-bsd
    agents:
      bsd: 'true'
    artifact_paths: bazel-bin/*bsd_*_stripped/k0s
  - label: bazel-bsd-arm
    command: make bazel-build-bsd-arm
    agents:
      bsd-arm: 'true'
    artifact_paths: bazel-bin/*bsd_*_stripped/k0s
  - label: bazel-darwin
    command: make bazel-build-darwin
    agents:
      darwin: 'true'
    artifact_paths: bazel-bin/darwin_*_stripped/k0s
  - label: bazel-windows
    command: make bazel-build-windows
    agents:
      windows: 'true'
    artifact_paths: bazel-bin/windows_*_stripped/k0s
  - label: bazel-android
    command: make bazel-build-android
    agents:
      android: 'true'
    artifact_paths: bazel-bin/android_*_stripped/k0s
