steps:
  - label: bazel-linux
    command: make bazel-build-linux
    agents:
      linux: 'true'
    artifact_paths: 'bin/**/*'
  - label: bazel-darwin
    command: make bazel-build-darwin
    agents:
      linux: 'true'
    artifact_paths: 'bin/**/*'
  - label: bazel-windows
    command: make bazel-build-windows
    agents:
      windows: 'true'
    artifact_paths: 'bin/**/*'
  - label: bazel-android
    command: make bazel-build-android
    agents:
      android: 'true'
    artifact_paths: 'bin/**/*'
