global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
- job_name: 'hub_and_agents'
  scheme: https
  file_sd_configs:
  - files:
    - 'prometheus_scrape_targets.json'

# Settings related to the remote write feature.
remote_write:
  - url: "https://prometheus-postgresql-adapter.k0s.io/write"
# - url: "http://prometheus-postgresql-adapter:9201/write"

# Settings related to the remote read feature.
remote_read:
  - url: "https://prometheus-postgresql-adapter.k0s.io/read"
# - url: "http://prometheus-postgresql-adapter:9201/read"
